### ISSUE TITLE
[Request] Total word count?

### ISSUE THREAD

**Issue by mrauril** [BasilPH/vizel#35]
Hello!

Is it possible to add a line to the stats command that displays total word count, similar to [this Keyboard Maestro Stats macro](https://forum.zettelkasten.de/discussion/786/zettelkasten-statistics)?

Thanks for all your work!

**Comment by BasilPH** [comment]
Hi @mrauril, thank you for reaching out! Please excuse the long time it took me to respond. I think adding the word count should be possible.

Do you think it's an issue if we count links as words as well? Something like `[text](url.com)` would probably be counted as two words.

**Comment by mrauril** [comment]
Hey no worries thanks for responding!  I don't think counting links is an issue since I don't think it would be 'double counting' because the link itself is part of the prose of the note. And I don't think its necessary to try to split them - only count [text] but not (url).

**Comment by BasilPH** [comment]
@mrauril, I started working on this, but I ran into some small issues with my development setup. I'll keep you posted.

**Comment by BasilPH** [comment]
@mrauril, thank you for your patience. If you run `pip install vizel==0.3.2b1` you can install the beta version which now displays a word count. Please let me know if this matches your expectations?
